# Generated by Django 4.0.4 on 2022-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/product'),
        ),
    ]
