# Generated by Django 4.1.dev20220429194355 on 2022-05-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_oder_size_product_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="oder", name="cart",),
        migrations.RemoveField(model_name="oder", name="product",),
        migrations.RemoveField(model_name="product", name="store",),
        migrations.DeleteModel(name="Cart",),
        migrations.DeleteModel(name="Oder",),
        migrations.DeleteModel(name="User",),
    ]
