# Generated by Django 4.1.dev20220429194355 on 2022-05-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_oder_cart_remove_oder_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantity",),
    ]
